# Generated by Django 5.2.4 on 2025-07-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile_is_online"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_pic",
        ),
    ]
