# Generated by Django 5.2.4 on 2025-10-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_privateroom_user1_alter_privateroom_user2"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="room_images/"),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
