# Generated by Django 5.2.4 on 2025-10-10 04:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_room_image_alter_room_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="privateroom",
            unique_together={("user1", "user2")},
        ),
    ]
