# Generated by Django 5.2.4 on 2025-07-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userprofile_bio_userprofile_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_online",
        ),
    ]
