# Generated by Django 5.2.4 on 2025-10-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status_privacy",
            field=models.CharField(default="everyone", max_length=50),
        ),
    ]
