# Generated by Django 5.2.4 on 2025-10-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_profile_status_privacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="read_receipts_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
