# Generated by Django 5.2.4 on 2025-10-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_profile_read_receipts_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="default_message_timer",
            field=models.IntegerField(default=0),
        ),
    ]
