# Generated by Django 5.2.4 on 2025-10-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_profile_default_message_timer"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="block_unknowns",
            field=models.BooleanField(default=False),
        ),
    ]
