# Generated by Django 5.2.4 on 2025-10-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_profile_block_unknowns"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="group_privacy",
            field=models.CharField(
                choices=[
                    ("everyone", "Everyone"),
                    ("contacts", "My Contacts"),
                    ("contacts_except", "My Contacts Except"),
                ],
                default="everyone",
                max_length=30,
            ),
        ),
    ]
