# Generated by Django 5.2.4 on 2025-10-13 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_profile_group_privacy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blocked_users",
            field=models.ManyToManyField(
                blank=True, related_name="blocked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
