# Generated by Django 5.2.4 on 2025-10-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_userprofile_blocked_users_userprofile_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo_privacy",
            field=models.CharField(
                choices=[
                    ("everyone", "Everyone"),
                    ("my_contacts", "My Contacts"),
                    ("my_contacts_except", "My Contacts Except"),
                    ("nobody", "Nobody"),
                ],
                default="everyone",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="read_receipts_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="status_privacy",
            field=models.CharField(default="everyone", max_length=50),
        ),
    ]
