# Generated by Django 5.2.4 on 2025-10-15 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_userprofile_photo_privacy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="blocked_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="blocked_by_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
