# Generated by Django 5.2.4 on 2025-10-16 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_userprofile_bio"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
