# Generated by Django 5.2.4 on 2025-10-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="app_lock_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
