# Generated by Django 5.2.4 on 2025-10-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_profile_app_lock_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="app_lock_password",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
