# Generated by Django 5.2.4 on 2025-10-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_profile_app_lock_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="app_lock_password_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
