# Generated by Django 5.2.4 on 2025-10-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_profile_app_lock_password_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="auto_download_audio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="auto_download_documents",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="auto_download_photos",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="auto_download_videos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="chat_wallpaper",
            field=models.ImageField(blank=True, null=True, upload_to="wallpapers/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="chat_wallpaper_default",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("gradient", "Gradient"),
                ],
                default="default",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="media_upload_quality",
            field=models.CharField(
                choices=[("high", "High Quality"), ("standard", "Standard Quality")],
                default="standard",
                max_length=10,
            ),
        ),
    ]
