# Generated by Django 5.2.4 on 2025-10-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_profile_auto_download_audio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="chat_wallpaper",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat_wallpapers/"
            ),
        ),
    ]
