# Generated by Django 5.2.4 on 2025-10-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_profile_chat_wallpaper"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="chat_theme",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("gradient", "Gradient"),
                ],
                default="default",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="chat_wallpaper_default",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
