# Generated by Django 5.2.4 on 2025-10-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_profile_chat_theme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="mute_notifications",
            field=models.BooleanField(default=False),
        ),
    ]
