# Generated by Django 5.2.4 on 2025-10-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatechatmessage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
