# Generated by Django 5.2.4 on 2025-10-21 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_privatechatmessage_is_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="privatechatmessage",
            name="deleted_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="deleted_private_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
