# Generated by Django 5.2.4 on 2025-10-28 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_room_members"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="chat_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
