# Generated by Django 5.2.4 on 2025-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_alter_room_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reply_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.TextField(blank=True, null=True),
        ),
    ]
