# Generated by Django 5.2.4 on 2025-10-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_message_reply_name_message_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatechatmessage",
            name="reply_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="privatechatmessage",
            name="reply_to",
            field=models.TextField(blank=True, null=True),
        ),
    ]
