# Generated by Django 5.2.4 on 2025-10-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_privatechatmessage_reply_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatechatmessage",
            name="reply_to_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
