# Generated by Django 5.2.4 on 2025-11-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_privatechatmessage_reply_to_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_forwarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="original_sender",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
