# Generated by Django 5.2.4 on 2025-11-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_message_is_forwarded_message_original_sender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatechatmessage",
            name="is_forwarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="privatechatmessage",
            name="original_sender",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
