# Generated by Django 5.2.4 on 2025-11-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_privatechatmessage_is_forwarded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="original_room_slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="privatechatmessage",
            name="original_room_slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
