# Generated by Django 5.2.4 on 2025-11-07 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_message_original_room_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="original_room_slug",
        ),
        migrations.RemoveField(
            model_name="privatechatmessage",
            name="original_room_slug",
        ),
    ]
