# Generated by Django 5.2.4 on 2025-11-16 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_remove_message_original_room_slug_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted_by",
            field=models.ManyToManyField(
                blank=True, related_name="deleted_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
