# Generated by Django 5.2.4 on 2025-11-16 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_hiddenroom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="hidden_by",
            field=models.ManyToManyField(
                blank=True, related_name="hidden_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
