# Generated by Django 5.2.4 on 2025-11-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_message_hidden_by"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HiddenRoom",
        ),
    ]
