# Generated by Django 5.2.4 on 2025-11-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_delete_hiddenroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
