# Generated by Django 5.2.4 on 2025-11-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_message_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatechatmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
