# Generated by Django 5.2.4 on 2026-05-23 00:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
